### ISSUE TITLE
Cannot read property 'pipe' of undefined     at dirtyCheck (ngneat-dirty-check-forms.js:88)

### ISSUE THREAD

**Issue by vishalsinghpoker** [ngneat/dirty-check-forms#11]
After installing this library and running the codebase, start getting this error.

Cannot read property 'pipe' of undefined at dirtyCheck (ngneat-dirty-check-forms.js:88)

**Comment by NetanelBasal** [comment]
Try to delete your node modules and the cache and reinstall it.

**Comment by vishalsinghpoker** [comment]
tried but nothing happens.

**Comment by vishalsinghpoker** [comment]
getting this error -
