### ISSUE TITLE
Cannot use `@ngneat/dirty-check-forms` in stackblitz

### ISSUE THREAD

**Issue by jogelin** [ngneat/dirty-check-forms#12]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I would like to use `@ngneat/dirty-check-forms` in stackblitz to reproduce an issue but it seems not compatible...

![image](https://user-images.githubusercontent.com/954509/131806653-c53ffc02-95d7-4fe8-9220-03a328edecba.png)

## Expected behavior

To work ;) 

## Minimal reproduction of the problem with instructions

Create a new Angular stackblitz and add the library

**Comment by NetanelBasal** [comment]
Try https://codesandbox.io/
