### ISSUE TITLE
Direct use of the global window object

### ISSUE THREAD

**Issue by FFKL** [ngneat/dirty-check-forms#13]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`dirtyCheck` operator uses global `window` object.
https://github.com/ngneat/dirty-check-forms/blob/944447a38ca4a507c6cae31f7bf5e79467c4dff3/libs/dirty-check-forms/src/lib/dirty-check.ts#L62-L64

## Expected behavior
I think, It's better to pass `window` option in config.

## What is the motivation / use case for changing the behavior?
Current behavior leads to restrictions on the use of SSR. Also it's impossible to apply `dirtyCheck` without  `beforeunload` event.

**Comment by FFKL** [comment]
@NetanelBasal Of course, I can implement it.

**Comment by NetanelBasal** [comment]
Go ahead
