### ISSUE TITLE
Upgrade to Angular 13 format

### ISSUE THREAD

**Issue by jogelin** [ngneat/dirty-check-forms#18]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using this library with Angular 13, I got this message:
```
Processing legacy "View Engine" libraries:
- @ngneat/dirty-check-forms [es2015/esm2015] (https://github.com/ngneat/dirty-check-forms)
- @ngneat/dirty-check-forms [module/esm5] (https://github.com/ngneat/dirty-check-forms)
- @ngneat/dirty-check-forms [main/umd] (https://github.com/ngneat/dirty-check-forms)
Encourage the library authors to publish an Ivy distribution.
```

So I am encouraging it :)

**Comment by NetanelBasal** [comment]
Do you want to run the command and create a PR :)

**Comment by shamoon** [comment]
@NetanelBasal Does [that](https://github.com/ngneat/dirty-check-forms/pull/16#issuecomment-1053931755) mean youre planning to address this one? Would be grateful for that, thanks for considering.

**Comment by shaharkazaz** [comment]
Fixed by https://github.com/ngneat/dirty-check-forms/commit/fa1e5f9c40b16e08b99626904c6188b6efd74229
