### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by st-clair-clarke** [ngneat/dirty-check-forms#2]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior
yarn add  @ngneat/dirty-check-forms

yarn add  @ngneat/dirty-check-forms should install the package
## Minimal reproduction of the problem with instructions
yarn install command gives error without installation
## What is the motivation / use case for changing the behavior?
error An unexpected error occurred: "EPERM: operation not permitted, lstat '..\node_modules\\@schematics\\update\\node_modules\\npm-package-arg\\node_modules'"

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  v13.3.0
- npm version 6.13.1
- Platform:  Windows 10

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
I just tried it and it works. It's not a library issue:

![image](https://user-images.githubusercontent.com/6745730/79851682-51f90f80-83ce-11ea-878e-f6e646e6ecb8.png)

**Comment by st-clair-clarke** [comment]
Thanks for your prompt reply. I think the copy-paste command included symbols that should not be there. Directly typing the command works.
