### ISSUE TITLE
StaticInjectorError(AppModule)[DirtyCheckGuard]: 

### ISSUE THREAD

**Issue by ng-model** [ngneat/dirty-check-forms#5]
## Error even after injecting in the provider, still throws this error. Please can you look into it ?

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
![image](https://user-images.githubusercontent.com/11791070/86398552-c9bba400-bc73-11ea-8fe5-4788e033f6a4.png)

## Minimal reproduction of the problem with instructions
just followed the instructions as described in the documentation.

## Environment
dev
<pre><code>
Angular version: 7.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X] Edge Version 83.0.478.56 (Official build) (64-bit)

**Comment by NetanelBasal** [comment]
Works for me. Create a reproduction example, please.

**Comment by ng-model** [comment]
Works for you? In Angular v7.x

**Comment by NetanelBasal** [comment]
No, I don't use v7. Please share the code.

**Comment by ng-model** [comment]
Couldn't do that!
