### ISSUE TITLE
the conform popup twice appears

### ISSUE THREAD

**Issue by subrat7** [ngneat/dirty-check-forms#7]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by danzrou** [comment]
Can you share a stackblitz reproducing this?

**Comment by fredericojesus** [comment]
Having the same issue.

**Comment by NetanelBasal** [comment]
Can you share a stackblitz reproducing this?

**Comment by NetanelBasal** [comment]
Closing this issue as there is no reproduction.
